enforce linting / formatting standards (#80)
magicuidesign/magicui pull request #99
Opened 2024-05-28 11:42 UTC by abdrahmanES1

2024-06-03 18:44 UTC, safethecode requested changes

2024-06-03 18:44 UTC, safethecode commented on .prettierrc
> +    "@ianvs/prettier-plugin-sort-imports"
typo 🥲
```suggestion
    "@trivago/prettier-plugin-sort-imports"
```

2024-06-03 18:48 UTC, safethecode commented
@dillionverma 
I think the Pull Request unit is too large. We need to verify if it working

2024-06-12 04:27 UTC, dillionverma commented
agreed I would prefer smaller PRs, but this gave me a lot of ideas of what to potentially try and how to setup prettier / linting

2024-06-15 22:52 UTC, alamenai commented
HI @abdrahmanES1 ,

If your changes are independent, please could you [cherry-pick ](https://git-scm.com/docs/git-cherry-pick) your commits and open pull requests with small changes.

I know the files changes are affected by the linter but a detailed description can be very helpful for the maintainers.

@dillionverma , what do you think about changing the target branch to `dev` and verify the changes through code spaces.

2024-07-01 16:03 UTC, closed without merging